### ISSUE TITLE
If hg.exe is not installed, this will exit with an error code when trying to submit

### ISSUE THREAD

**Issue by Eibwen** [Eibwen/LogstashTimer#1]
```C:\inetpub\wwwroot\uShipTrunk\uShip.Static>c:\inetpub\wwwroot\uShipTrunk\DevResources\LogstashTimer\LogstashTimer.exe /finish "bar"
ERROR: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at LogstashTimer.SourceControlInfo.GetProcessOutput(String processFilepath, String arguments)
   at LogstashTimer.SourceControlInfo.RunHgCommand(String arguments)
ERROR: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at LogstashTimer.SourceControlInfo.GetProcessOutput(String processFilepath, String arguments)
   at LogstashTimer.SourceControlInfo.RunHgCommand(String arguments)

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at LogstashTimer.TimerRecordBuilder.WithSourceControlInfo()
   at LogstashTimer.TimeRecorder.PublishRecord(String label)
   at LogstashTimer.Program.LogEvent(EventType event, IList`1 args)
   at LogstashTimer.Program.Main(String[] args)```

**Comment by Eibwen** [comment]
A workable solution in the parent to the successfully tagged commit
